# MULTITuDE dataset demo

In [12]:
from multitude import (
    load_dataframe,
    filter_dataframe,
    MultitudeDataset,
)

df = load_dataframe()
df.head()

,Unnamed: 0,text,label,multi_label,split,language,length,source
0,0,Якщо ви розумітельний сайт забезпечення продук...,1,opt-iml-max-30b,train,uk,26,MULTITuDE_MassiveSumm_interfax
1,1,В ходе дискуссий стороны договорились расширит...,1,aya-101,test,ru,125,MULTITuDE_MassiveSumm_dw
2,2,Az Európai Parlament (EP) bővítési stratégiájá...,1,Llama-2-70b-chat-hf,train,hu,150,MULTITuDE_MassiveSumm_24
3,3,"Da muss einer bizarre Mutproben bestehen, sich...",0,human,train,de,150,MassiveSumm_spiegel
4,4,"""El Ministro de Tecnología de la Información, ...",1,vicuna-13b,train,es,28,MULTITuDE_MassiveSumm_20minutos

In [13]:
df.shape

(206330, 8)

In [14]:
df["language"].value_counts()

language
ar    10367
cs    10351
hu    10349
nl    10344
pt    10344
bg    10340
de    10339
en    10338
ro    10335
hr    10335
es    10334
sl    10333
sk    10331
pl    10329
el    10328
ru    10327
uk    10324
zh    10309
gd    10276
ca     5283
ga     4714
Name: count, dtype: int64

In [15]:
df["multi_label"].value_counts()

multi_label
aya-101                     25948
human                       25945
Mistral-7B-Instruct-v0.2    25937
gpt-3.5-turbo-0125          25935
v5-Eagle-7B-HF              25892
vicuna-13b                  25876
opt-iml-max-30b             25568
Llama-2-70b-chat-hf         25229
Name: count, dtype: int64

In [16]:
df["split"].value_counts()

split
train    156240
test      50090
Name: count, dtype: int64

## Filtering

In [17]:
en_test_human = filter_dataframe(df, split="test", languages="en", binary_label=0)
en_test_human.shape

(299, 8)

In [18]:
de_gpt35 = filter_dataframe(df, languages="de", models="gpt-3.5-turbo-0125",
)
de_gpt35.head()

,Unnamed: 0,text,label,multi_label,split,language,length,source
95,95,Der ehemalige deutsche Bundeskanzler Gerhard S...,1,gpt-3.5-turbo-0125,train,de,164,MULTITuDE_MassiveSumm_n-tv
333,333,St. Pauli-Trainer Ewald Lienen hat das Schieds...,1,gpt-3.5-turbo-0125,train,de,123,MULTITuDE_MassiveSumm_welt
717,717,Die aktuelle Vogelgrippe-Epidemie sorgt für Ko...,1,gpt-3.5-turbo-0125,train,de,126,MULTITuDE_MassiveSumm_spiegel
844,844,Der renommierte Kameramann Haskell Wexler ist ...,1,gpt-3.5-turbo-0125,train,de,45,MULTITuDE_MassiveSumm_welt
932,932,In der Kunstwelt wird das Werk des österreichi...,1,gpt-3.5-turbo-0125,train,de,146,MULTITuDE_MassiveSumm_meinbezirk

## PyTorch Dataset

In [19]:
dataset = MultitudeDataset(split="train", languages=["en", "de"])
len(dataset), dataset[0]

(15905,
 {'text': 'Da muss einer bizarre Mutproben bestehen, sich vor Publikum zum Affen machen, um seine Freundschaft zu beweisen. Was bei "Circus Halligalli" nach wenigen Minuten erledigt war, haben Joko und Klaas für "Mein bester Feind" auf vier erschreckende Stunden ausgewalzt.Was tun, wenn plötzlich Roberto Blanco an der Tür klingelt? Was, wenn danach Joko Winterscheidt oder Klaas Heufer-Umlauf um die Ecke biegen? Wie rauskommen aus der Nummer, wenn das Filmteam doch eigens angereist ist, die Kameras schon aufgebaut sind? Im Grunde ist "Mein bester Feind" Nötigung mit Quotenfolge. Oder wie "Wetten, dass ..?!", nur ohne die lästigen Wetten. "Eine Sache ist ganz sicher", freute sich Winterscheidt am Anfang: "Es wird hochgradig peinlich heute Abend und, dafür stehe ich mit meinem Namen, auch dumm!" So richtig peinlich wurde es aber nicht, auch sah man schon Dümmeres.Der erste "Freund" erklärte sich bereit, auf der Zugspitze 998 Meter über dem Abgrund einen Kindervers zu rezitieren.',
  'label': 0,
  'multi_label': 'human',
  'split': 'train',
  'language': 'de',
  'length': 150,
  'source': 'MassiveSumm_spiegel'})

In [20]:
from torch.utils.data import DataLoader

loader = DataLoader(dataset, batch_size=4, shuffle=True)
next(iter(loader))

{'text': ['UNITED NATIONS - Israel’s prime minister urged the international community to place a “clear red line” on Iran’s controversial nuclear program as he addressed the U.N. General Assembly Thursday. Separately, Palestinian leader Mahmoud Abbas blasted Israel for its illegal settlement activity and said his government will seek upgraded U.N. status within the year. Israeli Prime Minister Benjamin Netanyahu said his country and much of the world are at risk from a potentially nuclear-armed Iran. He said the international community’s decade of negotiations with Iran over its nuclear program and the imposition of sanctions have not stopped Tehran from advancing its nuclear technology. “There is only one way to peacefully prevent Iran from getting atomic bombs - and that’s by placing a clear red line on Iran’s nuclear weapons program. Red lines don’t lead to war, red lines prevent war," said Netanyahu.Prime Minister Benjamin Netanyahu speaks during the 67th session of the United Nations General Assembly at U.N. headquarters, September 27, 2012.The Israeli leader said time is running out for the world to stop Iran. He used a cartoonish drawing of a bomb to explain that a red line must be drawn at Iran’s ability to enrich uranium, which he said is already beyond the 70 percent level. “And by next spring, at most by next summer, at current enrichment rates, they will have finished the medium enrichment and moved on to the final stage. From there it’s only a few months, possibly a few weeks, before they get enough enriched uranium for the first bomb," he said. His demand comes two days after U.S.',
  'Dieser Beitrag wurde am 29.10.2016 auf bento.de veröffentlicht.Der Pegida-Gründer Lutz Bachmann ist kein Freund von Einwanderung. Seine seit mittlerweile mehr als zwei Jahren montägliche Protestbewegung in Dresden warnt vor der "Islamisierung des Abendlandes" – und daher auch vor zu vielen Flüchtlingen aus dem Nahen Osten in Deutschland.Dass Bachmann selbst mal als Gefahr angesehen werden könnte, hat er hingegen sicher nicht gedacht. Seit Mai lebt er auf der spanischen Insel Teneriffa. Dort hat ihn nun das Parlament zur "unerwünschten Person" erklärt ("Sächsische Zeitung"). Wahrscheinlich fürchten sie eine Arisierung des Insellandes.Stimmung gegen Bachmann hat vor allem die Linkspartei Podemos gemacht. Podemos-Sprecher Fernando Sabaté sagte, Bachmann sei vor Ort "ein Virus". Er hingegen wolle "nie wieder Rassismus und Faschismus".Podemos hatte daher im lokalen Inselparlament um eine gemeinsame Resolution gebeten, Bachmann zu "unerwünschten Person" zu erklären. Alle Parteien schlossen sich dem Vorhaben an.Erstmal keine. Bachmann darf sich frei bewegen – die Resolution des Inselparlaments ist lediglich ein Fingerzeig.',
  'After days of intense negotiations, delegates at the United Nations Climate Change Conference in Glasgow have finally reached a historic agreement. The deal, known as the Glasgow Climate Pact, aims to accelerate action on reducing greenhouse gas emissions and limiting global warming to 1.5 degrees Celsius. Key points of the agreement include commitments to phase out coal use, increase financing for developing countries to cope with the impacts of climate change, and establish a mechanism for countries to regularly report on their progress towards meeting their emissions reduction targets. UN Secretary-General António Guterres praised the agreement as a "significant step forward" but also warned that much more work is needed to meet the goals of the Paris Agreement. The Glasgow Climate Pact will now be formally adopted by all 197 countries participating in the conference.',
  'Titel: Die Filmstiftung, ein wichtiger Förderer der deutschen Filmindustrie, feierte am Donnerstag Abend im Rahmen des Berlin Film Festivals sein 70-jähriges Jubiläum an der Spree. In einem festlich ausgestatteten Tent auf dem Berliner Festivalgelände schauten Hunderte Gäste auf die schimmernde Flusslandschaft hin, während Redner die Vergangenheit, Gegenwart und Zukunft der Filmstiftung besprachen.Im Vortrag "70 Jahre Filmstiftung: Die Geschichte einer Idee" nährte der Autor Christiane Erharter das Publikum mit interessanten Anekdoten und Fakten über die Entwicklung der Filmstiftung seit ihrer Gründung im Jahr 1952. Die Redner hoben hervor, dass die Filmstiftung als erste nationale Filmförderungseinrichtung der Bundesrepublik Deutschland maßgeblich an der Entwicklung der deutschen Filmlandschaft beteiligt war und sich weiterhin für die Förderung deutscher Filmproduktionen einsetzt.Nach dem Schluss der Reden gab es eine großartige Feier mit Essen, Getränken und einer livelosen Tanzveranstaltung. Die Gäste feierten die Filmstiftung und ihre langjährigen Erfolge bis in die späten Nachtstunden."Das war ein außerordentliches Ereignis. Die Filmstiftung ist ein großes Stück deutsche Kultur und es war ein großes Vergnügen, zu ihren 70. Geburtstag zu feiern," sagte ein besonders gerührter Gast.An diesem unvergesslichen Abend an der Spree wussten sich hunderte Filmfreunde und Förderer der Filmstiftung ein. Es war ein richtiges Treffpunkt, der einmal in einem Jahr stattfand, und die Erinnerungen an diesen Abend werden wahrscheinlich lange Zeit andauernd bleiben.'],
 'label': tensor([0, 0, 1, 1]),
 'multi_label': ['human',
  'human',
  'gpt-3.5-turbo-0125',
  'Mistral-7B-Instruct-v0.2'],
 'split': ['train', 'train', 'train', 'train'],
 'language': ['en', 'de', 'en', 'de'],
 'length': tensor([264, 154, 135, 212]),
 'source': ['MassiveSumm_voanews',
  'MassiveSumm_spiegel',
  'MULTITuDE_MassiveSumm_voanews',
  'MULTITuDE_MassiveSumm_welt']}