# MultiSocial dataset demo

In [1]:
from multisocial import (
    load_dataframe,
    filter_dataframe,
    MultiSocialDataset,
)

df = load_dataframe()
df.head()

,text,label,multi_label,split,language,length,source,potential_noise
0,"Hola, ¿qué tal? - ¿Qué tal?",1,aya-101,train,es,6,multisocial_discord,0
1,The breathtaking picture shared by [USER] is t...,1,v5-Eagle-7B-HF,train,en,10,multisocial_twitter,0
2,Πρέπει να πέσετε στην σ,1,opt-iml-max-30b,train,el,5,multisocial_telegram,0
3,"Дійсно, християнство передбачає дотримання пев...",1,gemini,train,uk,53,multisocial_telegram,0
4,I Your patience is still being put to the test...,1,Mistral-7B-Instruct-v0.2,train,cs,25,multisocial_telegram,0

In [2]:
df.shape

(472097, 8)

In [3]:
df["language"].value_counts()

language
es    50781
en    50756
pt    45178
nl    40605
de    30848
ro    24536
ru    24080
pl    23711
ar    23585
ca    21612
hr    20606
hu    20508
bg    20378
et    19913
cs    17267
zh    11404
uk    10388
el     7464
ga     3153
sl     3072
sk     2033
gd      219
Name: count, dtype: int64

In [4]:
df["multi_label"].value_counts()

multi_label
Mistral-7B-Instruct-v0.2    61305
v5-Eagle-7B-HF              61057
vicuna-13b                  60346
gemini                      59559
gpt-3.5-turbo-0125          58851
human                       57990
aya-101                     57566
opt-iml-max-30b             55423
Name: count, dtype: int64

In [5]:
df["source"].value_counts()

source
multisocial_telegram    155224
multisocial_discord      96287
multisocial_gab          70742
multisocial_twitter      64723
multisocial_whatsapp     27131
telegram                 22867
discord                  11498
gab                      10226
twitter                   9422
whatsapp                  3977
Name: count, dtype: int64

In [6]:
df["split"].value_counts()

split
train    331209
test     140888
Name: count, dtype: int64

In [7]:
df["potential_noise"].value_counts()

potential_noise
0    464600
1      7497
Name: count, dtype: int64

## Filtering

In [8]:
en_test_human = filter_dataframe(df, split="test", languages="en", binary_label=0)
en_test_human.shape

(1470, 8)

In [9]:
de_gemini = filter_dataframe(df, languages="de", models="gemini", exclude_noise=True)
de_gemini.head()

,text,label,multi_label,split,language,length,source,potential_noise
14,Auf Twitter treiben sich nur noch hirnlose Tro...,1,gemini,train,de,39,multisocial_gab,0
323,"""Eine Frau, vermutlich aus Somalia, schreit wi...",1,gemini,train,de,110,multisocial_telegram,0
859,"In glühender Ekstase brenne ich für dich, Karl...",1,gemini,test,de,166,multisocial_discord,0
913,"Na, hast du Durst auf ein kühles Blondes, das ...",1,gemini,train,de,94,multisocial_telegram,0
990,Verbrenne in der Hölle [USER]. Möge das höllis...,1,gemini,train,de,22,multisocial_discord,0

## PyTorch Dataset

In [10]:
dataset = MultiSocialDataset(split="train", languages=["en", "de"])
len(dataset), dataset[0]

(60271,
 {'text': 'The breathtaking picture shared by [USER] is truly a masterpiece.',
  'label': 1,
  'multi_label': 'v5-Eagle-7B-HF',
  'split': 'train',
  'language': 'en',
  'length': 10,
  'source': 'multisocial_twitter',
  'potential_noise': 0})

In [11]:
from torch.utils.data import DataLoader

loader = DataLoader(dataset, batch_size=4, shuffle=True)
next(iter(loader))

{'text': ['German political leaders have a poor record as moral authority.',
  "The searing inferno's edge, where flames dance a mesmerizing ballet of destruction. #molten #hellfire",
  '"Sie sage mir, Kollega ist so wie Rakhim"',
  'Good morning world. Its too early. Aber meine L�tte hat einen Spa� an diesen Nummern'],
 'label': tensor([1, 1, 1, 0]),
 'multi_label': ['aya-101', 'gemini', 'opt-iml-max-30b', 'human'],
 'split': ['train', 'train', 'train', 'train'],
 'language': ['en', 'en', 'de', 'de'],
 'length': tensor([10, 14,  8, 15]),
 'source': ['multisocial_gab',
  'multisocial_telegram',
  'multisocial_gab',
  'twitter'],
 'potential_noise': tensor([0, 0, 0, 0])}